
set(NSIS_CONFIG_FILE ${PROJECT_SOURCE_DIR}/BuildServer/NsisConfig.nsh)
file(WRITE   ${NSIS_CONFIG_FILE} "; Autogenerated file. Do not edit!\n")
file(APPEND ${NSIS_CONFIG_FILE} "!define VERSION_MAX \"${HG_MAJOR_VER}\"\n")
file(APPEND ${NSIS_CONFIG_FILE} "!define VERSION_MIN \"${HG_MINOR_VER}\"\n")
file(APPEND ${NSIS_CONFIG_FILE} "!define VERSION_REVISION \"${HG_REVISION_VER}\"\n")
file(APPEND ${NSIS_CONFIG_FILE} "!define VERSION \"${HG_MAJOR_VER}.${HG_MINOR_VER}.${HG_REVISION_VER}\"\n")
file(APPEND ${NSIS_CONFIG_FILE} "!define BIN_DIRECTORY \"${PROJECT_SOURCE_DIR}/Bin\"\n")
